### ISSUE TITLE
Machines do not recognize most recipes in version 1.1.3

### ISSUE THREAD

**Issue by ccpemily** [GregTechCEu/GregTechCEu-1.19#880]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.3

### Recipe Viewer Installed

JEI

### Environment

SMP/Dedicated Forge Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2，Mekanism，Embeddium, Oculus, Thermal Series, Hostile Neural Networks

### Expected Behavior

Machines works correctly with recipes that displayed in JEI

### Actual Behavior

Machines do not work even when the correct material supplied
![Q1](https://github.com/GregTechCEu/GregTech-Modern/assets/56390205/4e738d66-3b9b-474c-abf7-62f7f3687a18)
![Q2](https://github.com/GregTechCEu/GregTech-Modern/assets/56390205/610c140d-a6b4-4522-9aae-9d7fe8b4ab47)
![Q3](https://github.com/GregTechCEu/GregTech-Modern/assets/56390205/a71c60f2-0c8b-4bca-a0a1-255f180f8fc9)
![Q4](https://github.com/GregTechCEu/GregTech-Modern/assets/56390205/d7523282-1eb2-4de0-a5c1-dabdf3e4757f)

### Steps to Reproduce

Install GTCEuM 1.1.3
Put some Stainless Steel Ingot in Advanced Bender II with Programed Circuit 1, then power on

### Additional Information

Single ingredient recipe (tested Helium Gas to Liquid Helium) works properly but others not

**Comment by ccpemily** [comment]
Confirmed as a Cross-mod issue，but not sure for what caused this

**Comment by screret** [comment]
latest.log?

**Comment by ccpemily** [comment]
https://mclo.gs/BozA96t

I copied all the mods into a new pack and this issue resolved, but still exists in my current pack (with new level created). I'm checking config now, the logs show no significant errors at all.

**Comment by screret** [comment]
could you enable the `debug` config under the `dev` group in the GT config, and then send a log of loading the server?

**Comment by ccpemily** [comment]
[debug.log](https://github.com/GregTechCEu/GregTech-Modern/files/14177866/debug.log)

The log is here, I checked it but find nothing strange. 
The problem happens not only when the recipe requires a programming circuit, it is all gtce recipe wide, seems like the recipe check is not done at all. Machines only works when it already had a processing recipe when I enter the world or start the server, because of the priority of same recipe check when a recipe completes.
If I take out the ingredients, wait for machines done its work, then put back ingredients, it will stay silent and not do anything.

**Comment by screret** [comment]
Can you test on a pure forge server?

**Comment by screret** [comment]
Because it looks to me like arclight is messing up our mixins or something.

**Comment by ccpemily** [comment]
Okay, I'm testing it right now, the problem occurs in my forge server too. Will later send you log

**Comment by ccpemily** [comment]
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/14178348/latest.log)
[debug.log](https://github.com/GregTechCEu/GregTech-Modern/files/14178349/debug.log)

Here are the logs (opened all debug flag in gtceu.yaml), running on forge-47.2.16

**Comment by screret** [comment]
that's weird, there's no errors...

**Comment by ccpemily** [comment]
Machines have no problem to complete a recipe correctly, but the ingredients seems never checked. And my new pack start to have this proble too. Looks like it is not environment or level related, a weird cross mod problem

**Comment by ccpemily** [comment]
I tested 2 release: 1.1.2a-build476 has no problem, but 1.1.2a-build477 does have this problem.

**Comment by screret** [comment]
yes that's when I implemented the much faster recipe lookup, it shouldn't cause issues like this though as I fixed them while making the PR.

**Comment by screret** [comment]
could you do a binary search to find the breaking mod?

**Comment by ccpemily** [comment]
Sure but it could take time, I just reverted it back to build 476.

**Comment by ccpemily** [comment]
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/14181158/latest.log)
I have removed nearly half of mods but the problem still remains. And after I removed some mods, it starts to throw this crash (see above), even if I removed all other mods, only remain GTCEu

**Comment by screret** [comment]
that one I just fixed

**Comment by ccpemily** [comment]
Could you publish a fixed release? this issue seems to happen at build477 and above

**Comment by gri3229** [comment]
> Could you publish a fixed release? this issue seems to happen at build477 and above

I have exactly the same problem, I went back to a later version

**Comment by screret** [comment]
> Sure but it could take time, I just reverted it back to build 476.
